### ISSUE TITLE
ERR MODULE NOT FOUND

### ISSUE THREAD

**Issue by lianginx** [lianginx/chatgpt-nuxt#15]
I found an issue, after running `yarn build`, `node .output/server/index.mjs` will throw an error.

<img width="968" alt="image" src="https://github.com/lianginx/chatgpt-nuxt/assets/21002250/fdcf2fec-6d60-44b7-819c-95aa19c02011">

_Originally posted by @lianginx in https://github.com/lianginx/chatgpt-nuxt/issues/13#issuecomment-1549020478_

**Comment by itTkm** [comment]
@lianginx 
I'm also faced same issue when developping.
I have fixed bellow steps:

```bash
rm -rf node-modules
rm yarn.lock
yarn
```

**Comment by lianginx** [comment]
> @lianginx I have tested again with the following commands:
> 
> ```shell
> # remove old files
> rm -rf node_modules .nuxt .output yarn.lock
> 
> # build & production preview
> yarn && yarn build && yarn preview
> 
> # production
> docker-compose up -d # Start and run in the background.
> docker-compose down  # Stop and delete
> ```
> 
> It works fine in my environment.

This method is effective, thank you very much. It seems that a bad influence was caused by the historical file.
