### ISSUE TITLE
yarn dev error

### ISSUE THREAD

**Issue by wldst** [lianginx/chatgpt-nuxt#2]
(node:7156) UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:781:11)

**Comment by lianginx** [comment]
我觉得可能是你的 Node.js 版本过低导致的问题，使用 `node -v` 查看你的 Node.js 版本：

```bash
❯ node -v
v18.0.0
```

**Comment by lianginx** [comment]
> 我觉得可能是你的 Node.js 版本过低导致的问题，使用 `node -v` 查看你的 Node.js 版本：
> 
> ```shell
> ❯ node -v
> v18.0.0
> ```

不好意思，我测试之后发现确实运行不了，但问题跟你的好像不一样，而且好像并不是 Node.js 版本的问题。

你可以尝试在 `nuxt.config.ts` 中追加 `ssr: false`，关闭服务端渲染模式，关闭之后我遇到的问题就消失了，昨天我在 dev 分支的开发中也已经关闭了这个配置项。
