### ISSUE TITLE
【BUG】显示异常问题

### ISSUE THREAD

**Issue by 826675550** [lianginx/chatgpt-nuxt#26]
![image](https://github.com/lianginx/chatgpt-nuxt/assets/33411806/8b368bff-8dc2-4a20-84ab-5dff8b589ad1)

**Comment by 826675550** [comment]
> 哈哈，当发送第一条消息时会请 GPT-3.5 帮忙生成一个 **简短的标题**，看来似乎他不太听话，我抽空换一个提示词试试

好的， 非常感谢您的答复，有空的时候也处理一下滚动条的问题，在返回的代码块当中，如果代码过长出现了横向的滚动条，横向的滚动条无法使用，需拖动光标才可看到后面的内容
![image](https://github.com/lianginx/chatgpt-nuxt/assets/33411806/9cca916c-6312-4998-bfc4-35d17301965e)

**Comment by lianginx** [comment]
https://github.com/lianginx/chatgpt-nuxt/pull/29 已经解决聊天标题过长导致换行超出显示区域的问题
