### ISSUE TITLE
docker-compose打出来的镜像无法启动

### ISSUE THREAD

**Issue by zhenglin305** [lianginx/chatgpt-nuxt#32]
直接运行docker-compose up -d，容器无法启动，报错如下：
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xc925e0 node::Abort() [node]
 2: 0xc9265e  [node]
 3: 0xd0e1a9 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 4: 0xd0e2cc node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xc4fc04 node::V8Platform::Initialize(int) [node]
 6: 0xc4d448  [node]
 7: 0xc4d81b node::Start(int, char**) [node]
 8: 0x7fee2304918a  [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x7fee23049245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
10: 0xbabf4e _start [node]

有没有构建好的镜像可以直接用呢

**Comment by lianginx** [comment]
我测试后没有复现你这个问题，如果你是 Linux 系统，我猜测是不是你没有 [安装 Docker Compose 工具](https://docs.docker.com/compose/install/)，我记得 Linux 平台需要单独安装它

**Comment by zhenglin305** [comment]
我的是centos7，已经装了docker-compos的，之前别的项目都在用的
[root@Operations ~]#cd chatgpt-nuxt-master/
[root@Operations ~/chatgpt-nuxt-master]#ls
app.vue  assets  components  composables  docker-compose.yaml  docs  LICENSE  locales  nuxt.config.ts  package.json  pages  public  README.md  server  stores  tsconfig.json  types  utils
[root@Operations ~/chatgpt-nuxt-master]#docker-compose up -d
Creating network "chatgpt-nuxt-master_default" with the default driver
Pulling chatgpt-nux (node:latest)...
Trying to pull repository docker.io/library/node ... 
latest: Pulling from docker.io/library/node
bba7bb10d5ba: Pull complete
ec2b820b8e87: Pull complete
284f2345db05: Pull complete
fea23129f080: Pull complete
9063cd8e3106: Pull complete
cab57e1ea578: Pull complete
621a5c00039b: Pull complete
b322c70aa83e: Pull complete
Digest: sha256:2f0b0c15f97441defa812268ee943bbfaaf666ea6cf7cac62ee3f127906b35c6
Status: Downloaded newer image for docker.io/node:latest
Creating chatgpt-nuxt-master_chatgpt-nux_1 ... done
[root@Operations ~/chatgpt-nuxt-master]#docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                           PORTS                              NAMES
72cb731c1c57        node:latest         "docker-entrypoint..."   29 seconds ago      Restarting (139) 2 seconds ago                                      chatgpt-nuxt-master_chatgpt-nux_1
831f2acd266a        540a289bab6c        "nginx -g 'daemon ..."   2 years ago         Up 9 days                        80/tcp, 0.0.0.0:88-89->88-89/tcp   nginx

[root@Operations ~/chatgpt-nuxt-master]#docker logs chatgpt-nuxt-master_chatgpt-nux_1
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xc925e0 node::Abort() [node]
 2: 0xc9265e  [node]
 3: 0xd0e1a9 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 4: 0xd0e2cc node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xc4fc04 node::V8Platform::Initialize(int) [node]
 6: 0xc4d448  [node]
 7: 0xc4d81b node::Start(int, char**) [node]
 8: 0x7fee2304918a  [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x7fee23049245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
10: 0xbabf4e _start [node]
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xc925e0 node::Abort() [node]
 2: 0xc9265e  [node]
 3: 0xd0e1a9 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 4: 0xd0e2cc node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xc4fc04 node::V8Platform::Initialize(int) [node]
 6: 0xc4d448  [node]
 7: 0xc4d81b node::Start(int, char**) [node]
 8: 0x7f90d1b9718a  [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x7f90d1b97245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
10: 0xbabf4e _start [node]

**Comment by zhenglin305** [comment]
我的是centos7，已经装了docker-compos的，之前别的项目都在用的
[root@Operations ~]#cd chatgpt-nuxt-master/
[root@Operations ~/chatgpt-nuxt-master]#ls
app.vue  assets  components  composables  docker-compose.yaml  docs  LICENSE  locales  nuxt.config.ts  package.json  pages  public  README.md  server  stores  tsconfig.json  types  utils
[root@Operations ~/chatgpt-nuxt-master]#docker-compose up -d
Creating network "chatgpt-nuxt-master_default" with the default driver
Pulling chatgpt-nux (node:latest)...
Trying to pull repository docker.io/library/node ... 
latest: Pulling from docker.io/library/node
bba7bb10d5ba: Pull complete
ec2b820b8e87: Pull complete
284f2345db05: Pull complete
fea23129f080: Pull complete
9063cd8e3106: Pull complete
cab57e1ea578: Pull complete
621a5c00039b: Pull complete
b322c70aa83e: Pull complete
Digest: sha256:2f0b0c15f97441defa812268ee943bbfaaf666ea6cf7cac62ee3f127906b35c6
Status: Downloaded newer image for docker.io/node:latest
Creating chatgpt-nuxt-master_chatgpt-nux_1 ... done
[root@Operations ~/chatgpt-nuxt-master]#docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                           PORTS                              NAMES
72cb731c1c57        node:latest         "docker-entrypoint..."   29 seconds ago      Restarting (139) 2 seconds ago                                      chatgpt-nuxt-master_chatgpt-nux_1
831f2acd266a        540a289bab6c        "nginx -g 'daemon ..."   2 years ago         Up 9 days                        80/tcp, 0.0.0.0:88-89->88-89/tcp   nginx

[root@Operations ~/chatgpt-nuxt-master]#docker logs chatgpt-nuxt-master_chatgpt-nux_1
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xc925e0 node::Abort() [node]
 2: 0xc9265e  [node]
 3: 0xd0e1a9 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 4: 0xd0e2cc node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xc4fc04 node::V8Platform::Initialize(int) [node]
 6: 0xc4d448  [node]
 7: 0xc4d81b node::Start(int, char**) [node]
 8: 0x7fee2304918a  [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x7fee23049245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
10: 0xbabf4e _start [node]
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xc925e0 node::Abort() [node]
 2: 0xc9265e  [node]
 3: 0xd0e1a9 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 4: 0xd0e2cc node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xc4fc04 node::V8Platform::Initialize(int) [node]
 6: 0xc4d448  [node]
 7: 0xc4d81b node::Start(int, char**) [node]
 8: 0x7f90d1b9718a  [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x7f90d1b97245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
10: 0xbabf4e _start [node]

**Comment by lianginx** [comment]
我看这个历史记录，你是不是没有构建项目就直接部署了，要先安装依赖、构建项目之后再部署.

https://github.com/lianginx/chatgpt-nuxt/issues/33#issuecomment-1612809731

**Comment by zhenglin305** [comment]
不好意思，应该是我的docker环境有问题，我放到k8s上运行ok了
