### ISSUE TITLE
Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by wangpf09** [lianginx/chatgpt-nuxt#5]
启动项目配置api key执行无法正常使用

![image](https://user-images.githubusercontent.com/39894166/231175901-b248115d-2695-44d1-8598-41c4b898bf1f.png)

**Comment by lianginx** [comment]
这个 `data undefined` 报错是服务端捕获报错信息的代码写的有问题，我晚上改一下。

但服务端代码报错一般来说就是项目当前运行的网络环境有问题，需要一个梯子并且正确配置了代理，或者直接将项目运行在可以直连 OpenAI API 的服务器或电脑上。

**Comment by wangpf09** [comment]
好的，谢谢，我的电脑是配置了代理的但是这个程序一样是访问不出去，是否可以在代码层面添加上提供代理的接口呢发自我的手机-------- 原始邮件 --------发件人： Liang INX ***@***.***>日期： 2023年4月12日周三 17:25收件人： lianginx/chatgpt-nuxt ***@***.***>抄送： wangpf ***@***.***>, Author ***@***.***>主    题： Re: [lianginx/chatgpt-nuxt] Cannot read properties of undefined (reading 'data') (Issue #5)
这个 data undefined 报错是服务端捕获报错信息的代码写的有问题，我晚上改一下。
但服务端代码报错一般来说就是项目当前运行的网络环境有问题，需要一个梯子并且正确配置了代理，或者直接将项目运行在可以直连 OpenAI API 的服务器或电脑上。

**Comment by wangpf09** [comment]
好的，谢谢

**Comment by lianginx** [comment]
> 好的，谢谢

我查看了 Axios 文档，找到了如何使用代理发起请求，你可以看一下这里 #8
