### ISSUE TITLE
请问大佬，本地启动项目接口报错500，这个应该怎么处理呢

### ISSUE THREAD

**Issue by XiangXiaolong007** [lianginx/chatgpt-nuxt#6]
![WX20230413-150519@2x](https://user-images.githubusercontent.com/28032470/231680620-2c8e6bfb-4225-4a2e-ada4-bfc7b24494cd.png)

走vpn的代理也不行

**Comment by lianginx** [comment]
你可以尝试在配置代理后发起请求，具体请查看 #8
