### ISSUE TITLE
Appeared during the reply

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [lianginx/chatgpt-nuxt#7]
This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

**Comment by lianginx** [comment]
Sorry, my English is not good. Even after using translation software, I still didn't understand what you meant.

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱
