### ISSUE TITLE
How do I configure a proxy?

### ISSUE THREAD

**Issue by boloboloda** [lianginx/chatgpt-nuxt#8]
Hello， How do I configure a proxy?

**Comment by lianginx** [comment]
我在服务端代码部分使用了 [openai-node](https://github.com/openai/openai-node) 进行 API 调用，它内部是使用 Axios 发送网络请求。

所以关于如何使用代理，可以参考 Axios 的 AxiosRequestConfig 配置，我刚刚提交了一个版本，补充了如何使用代理的相关代码 99ef86f870268240a91fa0324c3dcfc389c769ef

**Comment by boloboloda** [comment]
谢谢你的帮助。
